# Claude Context Architect Configuration
# Deep Discovery Consultation System Settings

# =============================================================================
# CONSULTATION CONFIGURATION
# =============================================================================
consultation:
  # Time allocation for each phase (in minutes)
  time_allocation:
    research_phase: 
      minimum: 15
      maximum: 20
      default: 17
    consultation_phase:
      minimum: 20
      maximum: 30
      default: 25
    generation_phase:
      minimum: 10
      maximum: 15
      default: 12
    
  # Overall consultation timing
  total_duration:
    minimum: 45
    maximum: 65
    target: 54
    
  # Quality thresholds
  quality_gates:
    research_evidence_minimum: 3  # Minimum sources per recommendation
    consultation_completion_threshold: 90  # Percentage completion required
    context_improvement_minimum: 50  # Minimum improvement percentage
    user_satisfaction_minimum: 4.0  # Minimum satisfaction rating (1-5)

# =============================================================================
# RESEARCH CONFIGURATION  
# =============================================================================
research:
  repository_analysis:
    minimum_repositories: 10
    target_repositories: 20
    maximum_repositories: 50
    
  evidence_validation:
    craap_test_required: true
    minimum_sources: 3
    confidence_threshold: 0.7
    
  pattern_extraction:
    minimum_patterns: 50
    validation_rate_threshold: 0.9
    cross_reference_requirement: true

# =============================================================================
# CONTEXT ENGINE CONFIGURATION
# =============================================================================
context_engine:
  generation:
    file_structure: "hierarchical"  # hierarchical | flat | hybrid
    cross_references: true
    token_optimization: true
    
  validation:
    effectiveness_testing: true
    before_after_comparison: true
    improvement_threshold: 0.5  # 50% improvement minimum
    
  files:
    master_context: "CLAUDE.md"
    technical_context: "TECHNICAL-ARCHITECTURE.md"
    domain_context: "DOMAIN-KNOWLEDGE.md"
    patterns_context: "PROJECT-PATTERNS.md"
    workflow_context: "DEVELOPMENT-WORKFLOW.md"
    decisions_context: "DECISION-LOG.md"
    navigation_hub: "CONTEXT-NAVIGATION.md"

# =============================================================================
# AGENT FACTORY CONFIGURATION
# =============================================================================
agent_factory:
  core_agents:
    - name: "architecture_analyzer"
      specialization_required: true
    - name: "domain_expert" 
      specialization_required: true
    - name: "pattern_detective"
      specialization_required: true
    - name: "workflow_optimizer"
      specialization_required: true
    - name: "quality_guardian"
      specialization_required: true
    - name: "research_validator"
      specialization_required: true
      
  orchestration:
    parallel_execution: true
    conflict_resolution: "evidence_based"
    performance_monitoring: true
    
  development:
    template_system: true
    capability_boundaries: "strict"
    communication_protocols: "standardized"

# =============================================================================
# COMMAND FORGE CONFIGURATION
# =============================================================================
command_forge:
  generation:
    pattern_based: true
    convention_adherence: "strict"
    project_specific: true
    
  categories:
    component_generators: true
    test_creators: true
    api_builders: true
    debug_helpers: true
    workflow_automation: true
    
  optimization:
    usage_tracking: true
    performance_monitoring: true
    documentation_generation: true
    
  validation:
    convention_checking: true
    functionality_testing: true
    integration_testing: true

# =============================================================================
# ORCHESTRATION CONFIGURATION
# =============================================================================
orchestration:
  flow_management:
    phase_transitions: "smooth"
    progress_tracking: "real_time"
    checkpoint_system: true
    
  session_management:
    pause_resume: true
    state_persistence: true
    multi_session_support: true
    
  quality_assurance:
    end_to_end_testing: true
    performance_optimization: true
    error_recovery: "graceful"
    ux_refinement: true
    
  monitoring:
    usage_analytics: true
    performance_monitoring: true
    user_satisfaction_tracking: true

# =============================================================================
# SYSTEM CONFIGURATION
# =============================================================================
system:
  # Performance settings
  performance:
    token_optimization: true
    caching: true
    parallel_processing: true
    resource_monitoring: true
    
  # Error handling
  error_handling:
    graceful_degradation: true
    automatic_retry: true
    user_guidance: true
    state_recovery: true
    
  # Logging and monitoring
  logging:
    level: "info"  # debug | info | warn | error
    research_tracking: true
    consultation_recording: true
    generation_monitoring: true
    performance_logging: true
    
  # Security and privacy
  security:
    data_encryption: true
    session_security: true
    privacy_protection: true
    audit_logging: true

# =============================================================================
# CUSTOMIZATION SETTINGS
# =============================================================================
customization:
  # Adaptation levels
  adaptation:
    project_complexity: "auto_detect"  # simple | moderate | complex | auto_detect
    user_expertise: "adaptive"        # beginner | intermediate | expert | adaptive
    consultation_depth: "full"        # quick | standard | full | custom
    
  # Flexibility options
  flexibility:
    phase_reordering: true
    time_adjustment: true
    component_selection: true
    quality_threshold_adjustment: false  # Maintain quality standards
    
  # User preferences
  preferences:
    interaction_style: "professional"  # casual | professional | technical
    detail_level: "comprehensive"      # summary | detailed | comprehensive
    feedback_frequency: "regular"      # minimal | regular | verbose
    
# =============================================================================
# VALIDATION AND TESTING
# =============================================================================
validation:
  # Testing scenarios
  test_scenarios:
    simple_project: true
    complex_project: true
    team_project: true
    legacy_project: true
    
  # Success metrics
  success_metrics:
    completion_rate_minimum: 0.9
    satisfaction_minimum: 4.0
    time_accuracy_tolerance: 0.2  # 20% variance allowed
    quality_standards_maintained: true
    
  # Continuous improvement
  improvement:
    feedback_integration: true
    pattern_learning: true
    optimization_tracking: true
    user_experience_enhancement: true

# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================
environment:
  # Development settings
  development:
    debug_mode: false
    verbose_logging: false
    testing_mode: false
    
  # Production settings
  production:
    performance_optimization: true
    error_reporting: true
    analytics_collection: true
    
  # Integration settings
  integration:
    claude_code_native: true
    mcp_support: true
    external_tools: "selective"  # none | selective | full

# =============================================================================
# VERSION AND COMPATIBILITY
# =============================================================================
version:
  system_version: "1.0.0"
  config_version: "1.0.0"
  compatibility_mode: "claude_code_native"
  last_updated: "2025-08-07"
  
# =============================================================================
# FEATURE FLAGS
# =============================================================================
features:
  # Phase-specific features
  research_web_analysis: true
  consultation_session_management: true
  context_multi_file_generation: true
  agent_specialization_development: true
  command_project_specific_generation: true
  orchestration_full_coordination: true
  
  # Advanced features
  ai_pattern_recognition: true
  automatic_optimization: true
  collaborative_consultation: false  # Future feature
  enterprise_features: false        # Future feature

# =============================================================================
# END OF CONFIGURATION
# =============================================================================