# Claude Code Template Library - Project Configuration
project_config:
  version: "1.0"
  metadata:
    name: "[INSERT_PROJECT_NAME]"
    domain: "[INSERT_DOMAIN]"
    created: "$(date -u +%Y-%m-%d)"
    adaptation_mode: "not-started"
    readiness_score: 0
  
  placeholders:
    # Core placeholders - will be replaced during adaptation
    PROJECT_NAME: "[INSERT_PROJECT_NAME]"
    DOMAIN: "[INSERT_DOMAIN]"
    TECH_STACK: "[INSERT_TECH_STACK]"
    COMPANY_NAME: "[INSERT_COMPANY_NAME]"
    TEAM_SIZE: "[INSERT_TEAM_SIZE]"
    WORKFLOW_TYPE: "[INSERT_WORKFLOW_TYPE]"
    PRIMARY_LANGUAGE: "[INSERT_PRIMARY_LANGUAGE]"
    TESTING_FRAMEWORK: "[INSERT_TESTING_FRAMEWORK]"
    CI_CD_PLATFORM: "[INSERT_CI_CD_PLATFORM]"
    DEPLOYMENT_TARGET: "[INSERT_DEPLOYMENT_TARGET]"
    DATABASE_TYPE: "[INSERT_DATABASE_TYPE]"
    API_STYLE: "[INSERT_API_STYLE]"
    SECURITY_LEVEL: "[INSERT_SECURITY_LEVEL]"
    PERFORMANCE_PRIORITY: "[INSERT_PERFORMANCE_PRIORITY]"
    USER_BASE: "[INSERT_USER_BASE]"
  
  adaptations:
    applied: []
    # Adaptations will be tracked here
