[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python3 scripts/enable_performance_optimizations.py"

[deploy]
startCommand = "python3 -m claude_prompt_factory.core.server"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
ENVIRONMENT = "staging"
FRAMEWORK_VERSION = "2.0.0"
PERFORMANCE_MODE = "optimized"
CACHE_ENABLED = "true"
PARALLEL_LOADING = "true"
TOKEN_OPTIMIZATION = "true"
